### ISSUE TITLE
按照文档指引，一运行就报错了，出现了文件名称引用不正确

### ISSUE THREAD

**Issue by inksnowhailong** [AirPowerTeam/AirPower-Web#35]
![M V{7QE( K@U6@%6CP8Z~OR](https://github.com/user-attachments/assets/f6fa771c-5da0-4afa-8acf-83bbd10af047)
依照这个文档，进行初始化
![image](https://github.com/user-attachments/assets/c210599d-b6ef-4cd0-b3f5-a19e3aa14944)
但是这源代码的引用中，对应文件名称不正确，这是其中一个例子，多个位置都有文件名引用不对的情况

**Comment by HammCn** [comment]
已处理，系Gitee 代码没同步。
